---
# Ansible playbook for provisioning a web server on GCP (supports Debian/Ubuntu and RedHat/CentOS)
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure apt cache is updated (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install NGINX (Debian/Ubuntu)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure yum cache is updated (RedHat/CentOS)
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Install NGINX (RedHat/CentOS)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Open HTTP port (firewalld, if available)
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == 'RedHat'
      ignore_errors: yes

    - name: Open HTTP port (ufw, if available)
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == 'Debian'
      ignore_errors: yes
